### ISSUE TITLE
There is no Consigliere.jar

### ISSUE THREAD

**Issue by zachary-kaelan** [BenjaminUrquhart/Consigliere#3]
I have no idea what I'm supposed to do with this source. I ran the gradlew.bat but it didn't give me anything. I spent an hour trying to compile it myself in Eclipse but I gave up.

**Comment by BenjaminUrquhart** [comment]
I haven't updated the releases in some time. As for the build issues, what errors are you getting?

Note that this project relies on libpcap or the Windows equivalent (Npcap I believe) being installed on your system, so make sure you have that first.

**Comment by zachary-kaelan** [comment]
I have the caps. I don't know how to build it.


*Zachary Johnson*
.NET Developer

http://zjohnsonprogramming.weebly.com

Zachary.Kaelan@gmail.com

(919) 410-1240
